@startuml

skinparam linetype ortho

start

group "load + read version"
    :file-data<
    -> bin;

    :read version;
    if (check version supported) then (no)
        :report error;
        stop
    else (yes)
    endif

    -> bin;
end group

group "retrieve Proposal-Key"
    :read NumberOfAuthors;

    repeat :read Key;
        :try to decrypt Proposal-Key;
        if (decryption successful) then (yes)
            :keep key;
            break
        else (no)
        endif
    repeat while (more keys available) is (yes) not (no)
    if (got Proposal-Key) then (no)
        :report error;
        stop
    else (yes)
        :decrypt rest of file;
        -> bin;
    endif
end group

group "read autors"
    -> bin;
    repeat
    group "read author"
        :read name;
        :read mail;
        :read sign_pub_key;
        :read crypt_pub_key;
        :read sign_count;
        :read signature;
        :construct Author-Obj;
        :verify signature;
        if (check valid) then (no)
            :report warning;
            :discard;
        else (yes)
        endif
    end group
    repeat while (more authors) is (yes) not (no)
    -> Author[] + bin;
end group

group "read contents"
    -> bin;
    :read Genesis-Value;
    repeat :read type;

    switch (type)
    case (1)
    group "read Addendum"
        :read fields (HashOfPrevFrame, ..., Hash);
        :hash frame;
        if (hash match) then (yes)
            :construct Addendum-Obj;
            :store obj;
            -> Addendum;
        else (no)
            :report warning;
            :discard;
        endif
    end group

    case (2)
    group "read Vote"
        :read fields (HashOfPrevFrame, ..., Hash, Signature);
        :hash frame;
        if (hash match) then (yes)
            :verify signature;
            if (signature valid) then (yes)
                :construct Vote-Obj;
                :store obj;
                -> Vote;
            else (no)
                :report warning;
                :discard;
            endif
        else (no)
            :report warning;
            :discard;
        endif
    end group

    case (default)
        :report error;
        end
    endswitch
    repeat while (more data) is (yes) not (no)
    -> Addendum[] + Vote[];
end group

group "validate"
    -> Author[] + Addendum[] + Vote[];
    :order frames by hash-chain;

    :check if every frame (+ genesis) has exactly one child (except the last frame);
    :check if every timestamp is ascending;
    :check if every votes TargetAddendum exists;
    :check if every AuthorRef is valid;
    :check if every Addendum has >= 1 Vote;
    :check if user-clock is behind timestamp of last Addendum;
    :check if AuthorSignCount match;

    if (all checks passed) then (no)
        :report warning;
    else (yes)
    endif

    -> Proposal;
end group

stop

@enduml
